version: "3.8"
services:
  menu-service:
    build: ./menu-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - menu-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "3004:3004"
    depends_on:
      - mongo

  customer-service:
    build: ./customer-service
    ports:
      - "3005:3005"
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - inventory-service
      - customer-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
